apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  containers:
  - name: debug
    image: mahesh6419/debug:1.0.1
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
